application: hfwwg
version: 1
runtime: python27
api_version: 1

threadsafe: false

libraries:
- name: django
  version: "1.11"
- name: webapp2
  version: "2.5.2"

handlers:
- url: /.*
  script: hfwwg.app
  
